### ISSUE TITLE
iphone15pro  ios17 报错

### ISSUE THREAD

**Issue by q284985092** [FlutterPlayer/fplayer#22]
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(UNAVAILABLE, Battery info unavailable, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
<asynchronous suspension>
#2      __FPanel2State.getBatteryLevel (package:flutter_rural_revitalization/views/fvideo/MyfPanelBuilder.dart:414:19)

**Comment by biless** [comment]
升级了电池插件
